version: '3.4'

services:
  usermanagement:
    image: ${DOCKER_REGISTRY-}usermanagement
    build:
      context: .
      dockerfile: UserManagement/Dockerfile
    environment:
      AppSettings__ConnectionStrings__Db: "Server=akafoodsmysql;Port=3306;Database=akafoods_db;Uid=akafoods_main;Pwd=4K4_F@@ds_pWd"
    depends_on:
      - akafoodsmysql

  akafoodsmysql:
    image: mysql:8.0
    container_name: aka-foods-mysql
    ports:
      - "3306:3306"
      - "33060:33060"
    volumes:
      - aka_foods_mysql_volume:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: My_4k4_R00t_pwd
      MYSQL_DATABASE: akafoods_db
      MYSQL_USER: akafoods_main
      MYSQL_PASSWORD: 4K4_F@@ds_pWd

volumes:
  aka_foods_mysql_volume: