version: '3.4'

services:
  usermanagement:
    image: ${DOCKER_REGISTRY-}usermanagement
    build:
      context: .
      dockerfile: UserManagement/Dockerfile
    environment:
      AppSettings__ConnectionStrings__Db: "Server=mysqlserver;Port=3306;Database=akafood_db;Uid=akafood_main;Pwd=4K4_F@@d_pWd"
    depends_on:
      - mysqlserver

  mysqlserver:
    image: mysql:8
    container_name: aka-foods-mysql
    ports:
      - "3306:3306"
      - "33060:33060"
    volumes:
      - mysql_data:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: My_4k4_R00t_pwd
      MYSQL_DATABASE: akafood_db
      MYSQL_USER: akafood_main
      MYSQL_PASSWORD: 4K4_F@@d_pWd

volumes:
  mysql_data: